/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IRamsesV3PoolOwnerActions,
  IRamsesV3PoolOwnerActionsInterface,
} from "../../../../../../contracts-shadow/CL/core/interfaces/pool/IRamsesV3PoolOwnerActions";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "recipient",
        type: "address",
      },
      {
        internalType: "uint128",
        name: "amount0Requested",
        type: "uint128",
      },
      {
        internalType: "uint128",
        name: "amount1Requested",
        type: "uint128",
      },
    ],
    name: "collectProtocol",
    outputs: [
      {
        internalType: "uint128",
        name: "amount0",
        type: "uint128",
      },
      {
        internalType: "uint128",
        name: "amount1",
        type: "uint128",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint24",
        name: "_fee",
        type: "uint24",
      },
    ],
    name: "setFee",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "setFeeProtocol",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IRamsesV3PoolOwnerActions__factory {
  static readonly abi = _abi;
  static createInterface(): IRamsesV3PoolOwnerActionsInterface {
    return new Interface(_abi) as IRamsesV3PoolOwnerActionsInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IRamsesV3PoolOwnerActions {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as IRamsesV3PoolOwnerActions;
  }
}
