/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IMinimalVoter,
  IMinimalVoterInterface,
} from "../../../../contracts-shadow/src/interfaces/IMinimalVoter";

const _abi = [
  {
    inputs: [
      {
        internalType: "address[]",
        name: "_gauges",
        type: "address[]",
      },
      {
        internalType: "address[][]",
        name: "_tokens",
        type: "address[][]",
      },
      {
        internalType: "uint256[][]",
        name: "_nfpTokenIds",
        type: "uint256[][]",
      },
    ],
    name: "claimClGaugeRewards",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address[]",
        name: "_gauges",
        type: "address[]",
      },
      {
        internalType: "address[][]",
        name: "_tokens",
        type: "address[][]",
      },
      {
        internalType: "uint256[][]",
        name: "_nfpTokenIds",
        type: "uint256[][]",
      },
    ],
    name: "claimClGaugeRewardsAndExit",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "owner",
        type: "address",
      },
      {
        internalType: "address[]",
        name: "_feeDistributors",
        type: "address[]",
      },
      {
        internalType: "address[][]",
        name: "_tokens",
        type: "address[][]",
      },
    ],
    name: "claimIncentives",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "owner",
        type: "address",
      },
      {
        internalType: "address[]",
        name: "_feeDistributors",
        type: "address[]",
      },
      {
        internalType: "address[][]",
        name: "_tokens",
        type: "address[][]",
      },
    ],
    name: "claimLegacyIncentives",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address[]",
        name: "_gauges",
        type: "address[]",
      },
      {
        internalType: "address[][]",
        name: "_tokens",
        type: "address[][]",
      },
    ],
    name: "claimLegacyRewardsAndExit",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address[]",
        name: "_gauges",
        type: "address[]",
      },
      {
        internalType: "address[][]",
        name: "_tokens",
        type: "address[][]",
      },
    ],
    name: "claimRewards",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "pool",
        type: "address",
      },
    ],
    name: "gaugeForPool",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IMinimalVoter__factory {
  static readonly abi = _abi;
  static createInterface(): IMinimalVoterInterface {
    return new Interface(_abi) as IMinimalVoterInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IMinimalVoter {
    return new Contract(address, _abi, runner) as unknown as IMinimalVoter;
  }
}
