/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as pool from "./pool";
export type { pool };
export type { IRamsesV3Pool } from "./IRamsesV3Pool";
