/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface TestOracleVaultInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "getPrice"
      | "getSpotPrice"
      | "getTotalBalances"
      | "getTotalSupply"
      | "getValueInY"
      | "previewShares"
      | "setDeviationThreshold"
      | "setTotalBalances"
      | "setTotalSupply"
      | "setTwapInterval"
  ): FunctionFragment;

  encodeFunctionData(functionFragment: "getPrice", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "getSpotPrice",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getTotalBalances",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getTotalSupply",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getValueInY",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "previewShares",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setDeviationThreshold",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setTotalBalances",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setTotalSupply",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setTwapInterval",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(functionFragment: "getPrice", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getSpotPrice",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTotalBalances",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTotalSupply",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getValueInY",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "previewShares",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setDeviationThreshold",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setTotalBalances",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setTotalSupply",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setTwapInterval",
    data: BytesLike
  ): Result;
}

export interface TestOracleVault extends BaseContract {
  connect(runner?: ContractRunner | null): TestOracleVault;
  waitForDeployment(): Promise<this>;

  interface: TestOracleVaultInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  getPrice: TypedContractMethod<[], [bigint], "view">;

  getSpotPrice: TypedContractMethod<[], [bigint], "view">;

  getTotalBalances: TypedContractMethod<[], [[bigint, bigint]], "view">;

  getTotalSupply: TypedContractMethod<[], [bigint], "view">;

  getValueInY: TypedContractMethod<
    [amountX: BigNumberish, amountY: BigNumberish],
    [bigint],
    "view"
  >;

  previewShares: TypedContractMethod<
    [amountX: BigNumberish, amountY: BigNumberish],
    [
      [bigint, bigint, bigint] & {
        shares: bigint;
        effectiveX: bigint;
        effectiveY: bigint;
      }
    ],
    "view"
  >;

  setDeviationThreshold: TypedContractMethod<
    [threshold: BigNumberish],
    [void],
    "nonpayable"
  >;

  setTotalBalances: TypedContractMethod<
    [totalBalanceX: BigNumberish, totalBalanceY: BigNumberish],
    [void],
    "nonpayable"
  >;

  setTotalSupply: TypedContractMethod<
    [totalSupply: BigNumberish],
    [void],
    "nonpayable"
  >;

  setTwapInterval: TypedContractMethod<
    [twapInterval: BigNumberish],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "getPrice"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getSpotPrice"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getTotalBalances"
  ): TypedContractMethod<[], [[bigint, bigint]], "view">;
  getFunction(
    nameOrSignature: "getTotalSupply"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getValueInY"
  ): TypedContractMethod<
    [amountX: BigNumberish, amountY: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "previewShares"
  ): TypedContractMethod<
    [amountX: BigNumberish, amountY: BigNumberish],
    [
      [bigint, bigint, bigint] & {
        shares: bigint;
        effectiveX: bigint;
        effectiveY: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "setDeviationThreshold"
  ): TypedContractMethod<[threshold: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setTotalBalances"
  ): TypedContractMethod<
    [totalBalanceX: BigNumberish, totalBalanceY: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setTotalSupply"
  ): TypedContractMethod<[totalSupply: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setTwapInterval"
  ): TypedContractMethod<[twapInterval: BigNumberish], [void], "nonpayable">;

  filters: {};
}
