name: Validation Pipeline

on:
  pull_request:
    branches:
          - main
          - dev
          - production
          - 'releases/**'
          - $default-branch
  push:
    branches:
          - main
          - dev
          - production
          - 'releases/**'
          - $default-branch

jobs:
  # --- A: Contracts / Backend ---
  contracts-and-ui:
    name: Contract-lint-compile-test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Checout the git submodule (joe-v2 lib)
      - name: Checkout submodules
        run: git submodule update --init --recursive

      - name: Setup Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install deps (root)
        run: npm ci

      # Solidity
      - name: Lint Solidity
        run: npm run lint:sol

      # Hardhat compile & tests
      - name: Compile Contracts
        run: npx hardhat compile

      - name: Run Hardhat Tests
        run: npx hardhat test

      # UI part starts here
      - name: Install deps (UI)
        working-directory: UI/
        run: npm ci

      # Linting & formatting UI
      - name: Lint UI
        working-directory: UI/
        run: npm run lint

      - name: Build UI
        working-directory: UI/
        run: npm run build

      # (Optional) Run UI unit tests if we add some
      #- name: Run UI Tests
      #   working-directory: UI/
      #   run: npm test
